### ISSUE TITLE
Error swallowing?

### ISSUE THREAD

**Issue by jplock** [hotgazpacho/apollo-server-cache-dynamodb#4]
It appears like this library will shallow all errors thrown by DynamoDB which makes troubleshooting difficult.

https://github.com/hotgazpacho/apollo-server-cache-dynamodb/blob/master/src/index.ts#L56

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

**Comment by hotgazpacho** [comment]
I don't think that's the case. An exception thrown by DDB won't even get to the `then`. But maybe I don't understand how promises work...

**Comment by hotgazpacho** [comment]
Fixed in 338a83e, released as version 1.3.0
